version: 1
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
      - 2000000utok
      - 2000000uatom
  - name: bob
    coins:
      - 30000token
      - 300000000stake
  - name: dev
    coins: [100000token, 200000utok, 300000uatom, 400000stake]
    mnemonic: disease someone stand surface income long video stock script ripple strike bean
faucet:
  name: bob
  coins:
    - 4000token
    - 400000000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 100000000stake
