version: 1
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
      - 1000000000udredd
  - name: bob
    coins:
      - 30000token
      - 300000000stake
      - 1000000000udredd
  - name: dev
    coins: [999token, 9999999999stake, 1000000000udredd]
    mnemonic: disease someone stand surface income long video stock script ripple strike bean
  - name: john
    coins: [999token, 999999stake, 1000000000udredd]
    mnemonic: focus rookie copy baby laptop volcano cherry spend clutch suggest online auction
faucet:
  name: bob
  coins:
    - 4000token
    - 400000000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 100000000stake
genesis:
  app_state:
    gov:
      params:
        voting_period: "120s"
