version: 1
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 30000token
      - 300000000stake
faucet:
  name: bob
  coins:
    - 4000token
    - 400000000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 100000000stake
